import { IPullRequest } from "@/types/IPullRequest";

export const mockPullRequests: IPullRequest[] = [
  {
    pr_id: "1",
    repo: "user-management-system",
    pr_number: 142,
    title: "Add user authentication middleware",
    summary:
      "Implemented JWT-based authentication middleware to secure API endpoints",
    changes: [
      "Added middleware functions, updated route handlers, added JWT verification",
    ],
    impact: "High - Affects all authenticated routes",
    action_required: "Code review needed before merge",
    labels: ["security", "backend", "high-priority"],
    commit_messages: [
      "Add JWT middleware",
      "Update route handlers",
      "Add tests for auth",
    ],
    created_at: "2021-01-15T10:30:00Z",
    updated_at: "2021-01-16T14:20:00Z",
    status: "open",
    author: "john-doe",
    reviewers: ["jane-smith", "mike-wilson"],
  },
  {
    pr_id: "2",
    repo: "dashboard-frontend",
    pr_number: 89,
    title: "Redesign dashboard charts component",
    summary:
      "Updated chart library and redesigned dashboard visualization components",
    changes: [
      "Replaced Chart.js with Recharts, updated styling, improved responsiveness",
    ],
    impact: "Medium - Affects dashboard visualization",
    action_required: "UI/UX review required",
    labels: ["frontend", "ui", "enhancement"],
    commit_messages: [
      "Replace chart library",
      "Update dashboard styles",
      "Add responsive design",
    ],
    created_at: "2022-01-14T09:15:00Z",
    updated_at: "2022-01-16T11:45:00Z",
    status: "open",
    author: "jane-smith",
    reviewers: ["john-doe", "alex-chen"],
  },
  {
    pr_id: "3",
    repo: "api-gateway",
    pr_number: 203,
    title: "Fix rate limiting bug",
    summary:
      "Resolved issue where rate limiting was not properly applied to certain endpoints",
    changes: [
      "Updated rate limiting logic, fixed edge cases, added comprehensive tests",
    ],
    impact: "High - Critical bug fix for production",
    action_required: "Immediate deployment needed",
    labels: ["Bug", "critical", "backend"],
    commit_messages: [
      "Fix rate limiting logic",
      "Add edge case handling",
      "Update tests",
    ],
    created_at: "2023-01-16T08:00:00Z",
    updated_at: "2023-01-16T16:30:00Z",
    status: "merged",
    author: "mike-wilson",
    reviewers: ["john-doe"],
  },
  {
    pr_id: "4",
    repo: "mobile-app",
    pr_number: 67,
    title: "Implement dark mode theme",
    summary: "Added dark mode support across the mobile application",
    changes: [
      "Created theme system, updated all components, added theme toggle",
    ],
    impact: "Medium - Enhances user experience",
    action_required: "QA testing required",
    labels: ["mobile", "ui", "Feature"],
    commit_messages: [
      "Add theme system",
      "Update components for dark mode",
      "Add theme toggle",
    ],
    created_at: "2024-01-13T16:20:00Z",
    updated_at: "2024-01-15T13:10:00Z",
    status: "draft",
    author: "alex-chen",
    reviewers: ["jane-smith"],
  },
  {
    pr_id: "5",
    repo: "documentation",
    pr_number: 34,
    title: "Update API documentation",
    summary:
      "Comprehensive update to API documentation with new endpoints and examples",
    changes: ["Added new endpoint docs, updated examples, improved formatting"],
    impact: "Low - Documentation improvement",
    action_required: "Technical writer review",
    labels: ["Docs", "api"],
    commit_messages: [
      "Add new endpoint documentation",
      "Update examples",
      "Improve formatting",
    ],
    created_at: "2025-05-12T11:30:00Z",
    updated_at: "2025-01-14T09:45:00Z",
    status: "closed",
    author: "sarah-johnson",
    reviewers: ["mike-wilson"],
  },
];
